# Generated by Django 5.2.7 on 2025-10-16 14:11

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('email', models.EmailField(error_messages={'unique': 'funcionário com este e-mail já existe.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='e-mail')),
                ('cpf', models.CharField(error_messages={'unique': 'funcionário com este CPF já existe.'}, max_length=11, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('hire_date', models.DateField(verbose_name='data de admissão')),
                ('department', models.CharField(choices=[('engineering', 'Tecnologia'), ('finance', 'Financeiro'), ('hr', 'RH'), ('sales', 'Vendas'), ('marketing', 'Marketing'), ('operations', 'Operações'), ('support', 'Suporte')], max_length=100, verbose_name='departamento')),
                ('role', models.CharField(choices=[('analyst', 'Analista'), ('developer', 'Desenvolvedor'), ('tech_lead', 'Tech Lead'), ('manager', 'Gerente'), ('intern', 'Estagiário')], max_length=100, verbose_name='cargo')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='salário')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ['-created_at'],
            },
        ),
    ]
